FROM gradle:jdk21-jammy AS build
WORKDIR /app
COPY ../build.gradle settings.gradle ./
COPY ../src ./src
RUN gradle shadowJar --no-daemon

FROM amazoncorretto:21-alpine3.19-jdk
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
