version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wdpai
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
