version: '3.8'

services:
  app:
    build:
      dockerfile: devops/Dockerfile-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - private_network
    env_file:
      - .env

  db:
    build:
      dockerfile: devops/Dockerfile-postgresql
    ports:
      - "5432:5432"
    networks:
      - private_network
    env_file:
      - .env

networks:
  private_network: